import { jsPDF } from "jspdf";

import {
  CYCLE_TIME_TREND,
  DOMAIN_BREAKDOWN,
  EXCEPTIONS_BY_PARAMETER,
  MANAGEMENT_ALERTS,
  RECURRING_ISSUES,
} from "@/data/dashboard";
import { SITE_NAME } from "@/data/profiles";

/**
 * The batch review performance report, as a real PDF.
 *
 * Drawn with jsPDF rather than handed to the browser's print dialog: the
 * dialog puts a "Save as PDF" step, a paper-size choice and a set of
 * headers-and-footers the site did not ask for between the CQO and the file
 * they wanted. This produces the same document every time, on every machine.
 *
 * Everything on it is process data. Nothing measures a person, which is the
 * rule the dashboards are built on and the reason the footer repeats it on
 * every page.
 */

const A4 = { width: 210, height: 297 };
const MARGIN = 18;
const NAVY: [number, number, number] = [31, 56, 100];
const TOTAL_PAGES = 4;

const FOOTER_NOTE =
  "Cycle time measures total process time from review opened to authorisation. Individual reviewer activity is not tracked. This report is generated from QRA and is intended for internal quality review purposes.";

/** dd-Mmm-yyyy · HH:MM, the format the rest of the app uses. */
const stamp = (at: Date): string => {
  const months = [
    "Jan", "Feb", "Mar", "Apr", "May", "Jun",
    "Jul", "Aug", "Sep", "Oct", "Nov", "Dec",
  ];
  const pad = (value: number) => String(value).padStart(2, "0");

  return `${pad(at.getDate())}-${months[at.getMonth()]}-${at.getFullYear()} · ${pad(
    at.getHours(),
  )}:${pad(at.getMinutes())}`;
};

const reportReference = (at: Date): string =>
  `QRA-RPT-${at.getFullYear()}${String(at.getMonth() + 1).padStart(2, "0")}-001`;

interface Layout {
  doc: jsPDF;
  y: number;
}

const sectionHeading = (layout: Layout, text: string) => {
  layout.doc.setFont("helvetica", "bold");
  layout.doc.setFontSize(12);
  layout.doc.setTextColor(0, 0, 0);
  layout.doc.text(text, MARGIN, layout.y);
  layout.y += 6;
};

const paragraph = (layout: Layout, text: string, size = 10) => {
  layout.doc.setFont("helvetica", "normal");
  layout.doc.setFontSize(size);
  layout.doc.setTextColor(0, 0, 0);

  const lines = layout.doc.splitTextToSize(text, A4.width - MARGIN * 2);
  layout.doc.text(lines, MARGIN, layout.y);
  layout.y += lines.length * (size * 0.42) + 4;
};

/**
 * A plain bordered table. Column widths are given in millimetres so a long
 * exception description cannot push the status column off the page.
 */
const table = (
  layout: Layout,
  headings: string[],
  rows: string[][],
  widths: number[],
) => {
  const { doc } = layout;
  const rowHeight = 7;

  doc.setFillColor(240, 242, 245);
  doc.rect(MARGIN, layout.y - 5, A4.width - MARGIN * 2, rowHeight, "F");

  doc.setFont("helvetica", "bold");
  doc.setFontSize(9);
  doc.setTextColor(0, 0, 0);

  let x = MARGIN + 2;
  headings.forEach((heading, index) => {
    doc.text(heading, x, layout.y);
    x += widths[index];
  });
  layout.y += rowHeight;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);

  rows.forEach((row) => {
    x = MARGIN + 2;
    row.forEach((cell, index) => {
      const lines = doc.splitTextToSize(cell, widths[index] - 3);
      doc.text(lines.slice(0, 2), x, layout.y);
      x += widths[index];
    });

    doc.setDrawColor(224, 228, 232);
    doc.line(MARGIN, layout.y + 2, A4.width - MARGIN, layout.y + 2);
    layout.y += rowHeight;
  });

  layout.y += 4;
};

/** The same footer and page number on every page. */
const footer = (doc: jsPDF, page: number) => {
  doc.setFont("helvetica", "normal");
  doc.setFontSize(7);
  doc.setTextColor(110, 110, 110);

  const lines = doc.splitTextToSize(FOOTER_NOTE, A4.width - MARGIN * 2 - 24);
  doc.text(lines, MARGIN, A4.height - 16);

  doc.setFontSize(8);
  doc.text(`Page ${page} of ${TOTAL_PAGES}`, A4.width - MARGIN, A4.height - 10, {
    align: "right",
  });
};

export const buildAuditReport = (generatedBy: string): jsPDF => {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const now = new Date();
  const layout: Layout = { doc, y: 0 };

  /* ---- page 1 — cover -------------------------------------------------- */
  doc.setFillColor(...NAVY);
  doc.rect(0, 0, A4.width, 34, "F");

  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(16);
  doc.text("QRA — Quality Review Assistant", MARGIN, 15);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(12);
  doc.text("Batch Review Performance Report", MARGIN, 25);

  layout.y = 50;
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(10);

  const details: [string, string][] = [
    ["Site", SITE_NAME],
    ["Report period", "August 2026"],
    ["Generated", stamp(now)],
    ["Generated by", generatedBy],
    ["Report reference", reportReference(now)],
  ];

  details.forEach(([label, value]) => {
    doc.setFont("helvetica", "bold");
    doc.text(`${label}:`, MARGIN, layout.y);
    doc.setFont("helvetica", "normal");
    doc.text(value, MARGIN + 36, layout.y);
    layout.y += 7;
  });

  layout.y += 8;
  paragraph(
    layout,
    "This report summarises the analytical batch release review performance for the period shown. All data is sourced from Caliber LIMS, Waters Empower, and connected standalone instruments via QRA. Individual reviewer activity is not tracked. Cycle time is measured from review opened to authorisation.",
  );

  /* Signatures sit at the foot of the cover, above the footer note. */
  layout.y = A4.height - 78;
  sectionHeading(layout, "Signatures");
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);

  [
    "Prepared by QRA system:",
    "Reviewed by (QA Head):",
    "Approved by (Site Director):",
  ].forEach((role) => {
    doc.text(role, MARGIN, layout.y);
    doc.setDrawColor(120, 120, 120);
    doc.line(MARGIN + 58, layout.y + 1, MARGIN + 110, layout.y + 1);
    doc.text("Date:", MARGIN + 116, layout.y);
    doc.line(MARGIN + 128, layout.y + 1, A4.width - MARGIN, layout.y + 1);
    layout.y += 13;
  });

  footer(doc, 1);

  /* ---- page 2 — performance summary ------------------------------------ */
  doc.addPage();
  layout.y = MARGIN + 4;

  sectionHeading(layout, "Key Performance Indicators");
  table(
    layout,
    ["Metric", "Value", "Target", "Status"],
    [
      ["Avg Cycle Time", "1.8 days", "<= 2.0 days", "On target"],
      ["Right First Time", "94.2%", ">= 95%", "Below target"],
      ["SLA Compliance", "97.8%", ">= 98%", "Below target"],
      ["Batches Reviewed", "47", "—", "—"],
    ],
    [70, 34, 34, 36],
  );

  layout.y += 6;
  sectionHeading(layout, "Cycle Time Trend (Mar–Aug 2026)");
  table(
    layout,
    ["Month", "Cycle time"],
    CYCLE_TIME_TREND.map((point) => [point.month, `${point.days.toFixed(1)}d`]),
    [90, 84],
  );

  footer(doc, 2);

  /* ---- page 3 — exception analysis ------------------------------------- */
  doc.addPage();
  layout.y = MARGIN + 4;

  const totalExceptions = EXCEPTIONS_BY_PARAMETER.reduce(
    (sum, point) => sum + point.count,
    0,
  );

  sectionHeading(layout, "Exceptions by Test Parameter");
  table(
    layout,
    ["Test Parameter", "Occurrences", "% of Total"],
    [
      ...RECURRING_ISSUES.map((issue) => [
        issue.issue,
        String(issue.occurrences),
        issue.share,
      ]),
      ["Total", String(totalExceptions), "100%"],
    ],
    [96, 40, 38],
  );

  layout.y += 4;
  sectionHeading(layout, "Recurring Review Issues");

  const [first, second, third] = RECURRING_ISSUES;
  paragraph(
    layout,
    `${first.issue} accounts for ${first.share} of all ${totalExceptions} review exceptions raised this month, ahead of ${second.issue} at ${second.share} and ${third.issue} at ${third.share}. Together these three account for ${
      first.occurrences + second.occurrences + third.occurrences
    } of ${totalExceptions}. The concentration in related substances points at method and stability behaviour rather than at isolated handling errors; the standards and chemicals findings are records questions, where the material was fit and its traceability was incomplete.`,
  );

  layout.y += 2;
  sectionHeading(layout, "Open Alerts");
  table(
    layout,
    ["Alert", "Severity", "AR Number", "Detail"],
    MANAGEMENT_ALERTS.map((alert) => {
      const [ar, ...rest] = alert.detail.split(" · ");
      return [
        alert.label,
        alert.severity === "high" ? "Critical" : "Warning",
        ar,
        rest.join(" · "),
      ];
    }),
    [40, 26, 40, 68],
  );

  footer(doc, 3);

  /* ---- page 4 — domain breakdown --------------------------------------- */
  doc.addPage();
  layout.y = MARGIN + 4;

  sectionHeading(layout, "Review Type Breakdown");
  table(
    layout,
    ["Domain", "Completed", "Avg Days", "Exceptions"],
    DOMAIN_BREAKDOWN.map((row) => [
      row.domain,
      String(row.completed),
      row.avgDays,
      String(row.exceptions),
    ]),
    [70, 34, 34, 36],
  );

  footer(doc, 4);

  return doc;
};

export const downloadAuditReport = (generatedBy: string) => {
  const now = new Date();
  buildAuditReport(generatedBy).save(`${reportReference(now)}.pdf`);
};
