import { jsPDF } from "jspdf";

import {
  CYCLE_TIME_TREND,
  DOMAIN_BREAKDOWN,
  EXCEPTIONS_BY_PARAMETER,
  MANAGEMENT_ALERTS,
  RECURRING_ISSUES,
} from "@/data/dashboard";
import { SITE_NAME } from "@/data/profiles";
import {
  coverHeader,
  detailRows,
  footer,
  Layout,
  MARGIN,
  paragraph,
  sectionHeading,
  signatureBlock,
  stamp,
  table,
} from "@/lib/pdf-report";

/**
 * The batch review performance report, as a real PDF.
 *
 * Drawn with jsPDF rather than handed to the browser's print dialog: the
 * dialog puts a "Save as PDF" step, a paper-size choice and a set of
 * headers-and-footers the site did not ask for between the CQO and the file
 * they wanted. This produces the same document every time, on every machine.
 *
 * Everything on it is process data. Nothing measures a person, which is the
 * rule the dashboards are built on and the reason the footer repeats it on
 * every page.
 */

const TOTAL_PAGES = 4;

const reportReference = (at: Date): string =>
  `QRA-RPT-${at.getFullYear()}${String(at.getMonth() + 1).padStart(2, "0")}-001`;

export const buildAuditReport = (generatedBy: string): jsPDF => {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const now = new Date();
  const layout: Layout = { doc, y: 0 };

  /* ---- page 1 — cover -------------------------------------------------- */
  coverHeader(doc, "Batch Review Performance Report");

  layout.y = 50;
  detailRows(layout, [
    ["Site", SITE_NAME],
    ["Report period", "August 2026"],
    ["Generated", stamp(now)],
    ["Generated by", generatedBy],
    ["Report reference", reportReference(now)],
  ]);

  layout.y += 8;
  paragraph(
    layout,
    "This report summarises the analytical batch release review performance for the period shown. All data is sourced from Caliber LIMS, Waters Empower, and connected standalone instruments via QRA. Individual reviewer activity is not tracked. Cycle time is measured from review opened to authorisation.",
  );

  /* Signatures sit at the foot of the cover, above the footer note. */
  signatureBlock(layout, [
    "Prepared by QRA system:",
    "Reviewed by (QA Head):",
    "Approved by (Site Director):",
  ]);

  footer(doc, 1, TOTAL_PAGES);

  /* ---- page 2 — performance summary ------------------------------------ */
  doc.addPage();
  layout.y = MARGIN + 4;

  sectionHeading(layout, "Key Performance Indicators");
  table(
    layout,
    ["Metric", "Value", "Target", "Status"],
    [
      ["Avg Cycle Time", "1.8 days", "<= 2.0 days", "On target"],
      ["Right First Time", "94.2%", ">= 95%", "Below target"],
      ["SLA Compliance", "97.8%", ">= 98%", "Below target"],
      ["Batches Reviewed", "47", "—", "—"],
    ],
    [70, 34, 34, 36],
  );

  layout.y += 6;
  sectionHeading(layout, "Cycle Time Trend (Mar–Aug 2026)");
  table(
    layout,
    ["Month", "Cycle time"],
    CYCLE_TIME_TREND.map((point) => [point.month, `${point.days.toFixed(1)}d`]),
    [90, 84],
  );

  footer(doc, 2, TOTAL_PAGES);

  /* ---- page 3 — exception analysis ------------------------------------- */
  doc.addPage();
  layout.y = MARGIN + 4;

  const totalExceptions = EXCEPTIONS_BY_PARAMETER.reduce(
    (sum, point) => sum + point.count,
    0,
  );

  sectionHeading(layout, "Exceptions by Test Parameter");
  table(
    layout,
    ["Test Parameter", "Occurrences", "% of Total"],
    [
      ...RECURRING_ISSUES.map((issue) => [
        issue.issue,
        String(issue.occurrences),
        issue.share,
      ]),
      ["Total", String(totalExceptions), "100%"],
    ],
    [96, 40, 38],
  );

  layout.y += 4;
  sectionHeading(layout, "Recurring Review Issues");

  const [first, second, third] = RECURRING_ISSUES;
  paragraph(
    layout,
    `${first.issue} accounts for ${first.share} of all ${totalExceptions} review exceptions raised this month, ahead of ${second.issue} at ${second.share} and ${third.issue} at ${third.share}. Together these three account for ${
      first.occurrences + second.occurrences + third.occurrences
    } of ${totalExceptions}. The concentration in related substances points at method and stability behaviour rather than at isolated handling errors; the standards and chemicals findings are records questions, where the material was fit and its traceability was incomplete.`,
  );

  layout.y += 2;
  sectionHeading(layout, "Open Alerts");
  table(
    layout,
    ["Alert", "Severity", "AR Number", "Detail"],
    MANAGEMENT_ALERTS.map((alert) => {
      const [ar, ...rest] = alert.detail.split(" · ");
      return [
        alert.label,
        alert.severity === "high" ? "Critical" : "Warning",
        ar,
        rest.join(" · "),
      ];
    }),
    [40, 26, 40, 68],
  );

  footer(doc, 3, TOTAL_PAGES);

  /* ---- page 4 — domain breakdown --------------------------------------- */
  doc.addPage();
  layout.y = MARGIN + 4;

  sectionHeading(layout, "Review Type Breakdown");
  table(
    layout,
    ["Domain", "Completed", "Avg Days", "Exceptions"],
    DOMAIN_BREAKDOWN.map((row) => [
      row.domain,
      String(row.completed),
      row.avgDays,
      String(row.exceptions),
    ]),
    [70, 34, 34, 36],
  );

  footer(doc, 4, TOTAL_PAGES);

  return doc;
};

export const downloadAuditReport = (generatedBy: string) => {
  const now = new Date();
  buildAuditReport(generatedBy).save(`${reportReference(now)}.pdf`);
};
