import { jsPDF } from "jspdf";

import {
  DOMAIN_RELEASE_PROGRESS,
  PENDING_BY_REASON,
  PIPELINE_KPIS,
  STABILITY_OUT_OF_WINDOW,
  STABILITY_WINDOW_STATUS,
} from "@/data/dashboard";
import { SITE_NAME } from "@/data/profiles";
import {
  coverHeader,
  detailRows,
  footer,
  Layout,
  MARGIN,
  paragraph,
  sectionHeading,
  share,
  signatureBlock,
  stamp,
  table,
} from "@/lib/pdf-report";

/**
 * The QA operations report, as a real PDF.
 *
 * The GM-QA's counterpart to the CQO's performance report: where that one
 * answers how well the review process is running, this one answers where the
 * samples are and what is holding them. Every figure is read from the same
 * constants the dashboard renders, so the paper and the screen cannot
 * disagree — a report that quietly drifts from the system it summarises is
 * worse than no report.
 *
 * Nothing on it measures a person. Cycle time is process time.
 */

const TOTAL_PAGES = 4;
const REPORT_REFERENCE = "QRA-OPS-202608-001";

/**
 * Investigations open against the site.
 *
 * Stated here rather than read from QUALITY_EVENTS: the dashboard cards pair
 * an active count with a free-text detail line ("Raised this month: 3"),
 * which does not decompose into an Active / Closed pair without guessing.
 */
const QUALITY_EVENT_ROWS: string[][] = [
  ["Process Non-Conformances (PNCs)", "7", "3"],
  ["OOS Investigations", "2", "1"],
  ["Out of Trend (OOT)", "4", "2"],
];

export const buildOperationsReport = (generatedBy: string): jsPDF => {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const now = new Date();
  const layout: Layout = { doc, y: 0 };

  /* ---- page 1 — cover -------------------------------------------------- */
  coverHeader(doc, "QA Operations Report");

  layout.y = 50;
  detailRows(layout, [
    ["Site", SITE_NAME],
    ["Report period", "August 2026"],
    ["Generated", stamp(now)],
    ["Generated by", generatedBy],
    ["Report reference", REPORT_REFERENCE],
  ]);

  layout.y += 8;
  paragraph(
    layout,
    "This report summarises the analytical sample pipeline status and quality event metrics for the period shown. Data is sourced from Caliber LIMS via NeuraTrace. Individual reviewer activity is not tracked. Cycle time is measured from review opened to authorisation.",
  );

  signatureBlock(layout, [
    "Prepared by NeuraTrace system:",
    "Reviewed by (GM-QA):",
    "Approved by (QA Head):",
  ]);

  footer(doc, 1, TOTAL_PAGES);

  /* ---- page 2 — pipeline status ---------------------------------------- */
  doc.addPage();
  layout.y = MARGIN + 4;

  /* The first pipeline stat is the total the rest are shares of. */
  const totalSamples = Number(PIPELINE_KPIS[0].value);

  sectionHeading(layout, "Sample Pipeline — August 2026");
  table(
    layout,
    ["Stage", "Count", "% of Total"],
    PIPELINE_KPIS.map((stat, index) => [
      stat.title,
      stat.value,
      index === 0 ? "100%" : share(Number(stat.value), totalSamples),
    ]),
    [96, 40, 38],
  );

  layout.y += 6;
  sectionHeading(layout, "Stability Samples — Out of Window");
  table(
    layout,
    ["AR Number", "Product", "Stage", "Scheduled", "Overdue", "Action"],
    STABILITY_OUT_OF_WINDOW.map((row) => [
      row.arNumber,
      row.product,
      row.stage,
      row.scheduled,
      `${row.daysOverdue} days`,
      row.action,
    ]),
    [30, 34, 18, 26, 20, 46],
  );

  /* The dashboard writes its window rules with plus-minus signs, which are
     outside the WinAnsi set the PDF fonts use. Same rules, spelled out. */
  paragraph(
    layout,
    `Window rules: ${STABILITY_WINDOW_STATUS.subheading
      .replace(/±/g, "+-")
      .replace(/ · /g, " | ")}`,
    9,
  );

  footer(doc, 2, TOTAL_PAGES);

  /* ---- page 3 — quality events and pending analysis --------------------- */
  doc.addPage();
  layout.y = MARGIN + 4;

  sectionHeading(layout, "Quality Events — August 2026");
  table(
    layout,
    ["Event Type", "Active", "Closed This Month"],
    QUALITY_EVENT_ROWS,
    [96, 40, 38],
  );

  layout.y += 6;

  const totalPending = PENDING_BY_REASON.reduce(
    (sum, reason) => sum + reason.samples,
    0,
  );

  sectionHeading(layout, "Pending Analysis — Reason Breakdown");
  table(
    layout,
    ["Reason", "Samples Pending", "% of Pending"],
    [
      ...PENDING_BY_REASON.map((reason) => [
        reason.reason,
        String(reason.samples),
        share(reason.samples, totalPending),
      ]),
      ["Total pending", String(totalPending), "100%"],
    ],
    [96, 40, 38],
  );

  paragraph(
    layout,
    "Instrument downtime accounts for more than half of all pending analysis. HPLC-002, KFA2004 and LCMS are the primary affected instruments.",
    9,
  );

  footer(doc, 3, TOTAL_PAGES);

  /* ---- page 4 — domain release progress -------------------------------- */
  doc.addPage();
  layout.y = MARGIN + 4;

  const totals = DOMAIN_RELEASE_PROGRESS.reduce(
    (sum, row) => ({
      samplesIn: sum.samplesIn + row.samplesIn,
      completed: sum.completed + row.completed,
      pending: sum.pending + row.pending,
      /* Weighted by volume: a domain doing 332 samples moves the site
         average further than one doing 67. */
      dayLoad: sum.dayLoad + row.samplesIn * parseFloat(row.avgDays),
    }),
    { samplesIn: 0, completed: 0, pending: 0, dayLoad: 0 },
  );

  sectionHeading(layout, "Domain Release Progress — August 2026");
  table(
    layout,
    ["Domain", "Samples In", "Completed", "Pending", "% Complete", "Avg Days"],
    [
      ...DOMAIN_RELEASE_PROGRESS.map((row) => [
        row.domain,
        String(row.samplesIn),
        String(row.completed),
        String(row.pending),
        `${row.percentComplete}%`,
        row.avgDays,
      ]),
      [
        "Total",
        String(totals.samplesIn),
        String(totals.completed),
        String(totals.pending),
        share(totals.completed, totals.samplesIn),
        `${(totals.dayLoad / totals.samplesIn).toFixed(1)}d`,
      ],
    ],
    [42, 26, 26, 24, 28, 28],
  );

  layout.y += 6;
  sectionHeading(layout, "Summary Observation");
  paragraph(
    layout,
    "Packing Material leads release progress at 93% completion with the lowest average cycle time of 1.3 days. Finished Product and IPFP are below 85% completion; IPFP carries the highest average cycle time at 2.4 days, driven by the in-process testing requirement. Stability volume is the largest at 332 samples with 45 pending, of which 3 are out of the stability window and require immediate attention.",
  );

  footer(doc, 4, TOTAL_PAGES);

  return doc;
};

export const downloadOperationsReport = (generatedBy: string) => {
  buildOperationsReport(generatedBy).save(`${REPORT_REFERENCE}.pdf`);
};
