import { jsPDF } from "jspdf";

import {
  applicableSections,
  CHECKLIST_REFERENCES,
  SECTION_LABELS,
  sectionRecordLabel,
  type Batch,
  type Section,
} from "@/data/batches";

/**
 * Text-based PDF rather than a canvas capture: selectable, searchable, small,
 * and legible at print resolution — what an auditor needs from a record.
 *
 * Vocabulary here matters as much as on screen: never "Pass", "Approved" or
 * "Released". A test is Compliant or Needs Review; disposition stays in Caliber.
 */

const MARGIN = 48;
const PAGE_W = 595.28; // A4 portrait, points
const PAGE_H = 841.89;
const BODY_W = PAGE_W - MARGIN * 2;

const FOOTER =
  "Generated by QRA — Read only record. QA disposition and release decision recorded in Caliber LIMS.";

type SectionStatusMap = Record<string, Record<string, string>>;

export interface RecordInput {
  batch: Batch;
  sectionStatuses: SectionStatusMap;
  reviewDate: string;
  slaLabel: string;
  reviewerNotes: string;
}

/** Splits "Analytical Checklist Item 5a — Chemical usage verified". */
export function splitChecklistReference(reference: string): {
  ref: string;
  description: string;
} {
  const [head, ...rest] = reference.split(" — ");
  return {
    ref: head.replace(/^Analytical Checklist /, ""),
    description: rest.join(" — "),
  };
}

/** Reviewed / Needs Review / N/A for one section. Never "Pending". */
export function checklistStatus(
  section: Section,
  statuses: Record<string, string> | undefined,
): "Reviewed" | "Needs Review" | "N/A" {
  if (!section.applicable) return "N/A";
  return statuses?.[section.type] === "Reviewed" ? "Reviewed" : "Needs Review";
}

export function buildReviewRecord({
  batch,
  sectionStatuses,
  reviewDate,
  slaLabel,
  reviewerNotes,
}: RecordInput): jsPDF {
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  let y = MARGIN;
  let page = 1;

  const footer = () => {
    doc.setFontSize(7);
    doc.setTextColor(120);
    doc.text(FOOTER, MARGIN, PAGE_H - 28);
    doc.text(`Page ${page}`, PAGE_W - MARGIN, PAGE_H - 28, { align: "right" });
    doc.setTextColor(0);
  };

  const room = (needed: number) => {
    if (y + needed <= PAGE_H - 58) return;
    footer();
    doc.addPage();
    page += 1;
    y = MARGIN;
  };

  const heading = (text: string) => {
    room(34);
    doc.setFontSize(11);
    doc.setFont("helvetica", "bold");
    doc.text(text, MARGIN, y);
    doc.setFont("helvetica", "normal");
    y += 6;
    doc.setDrawColor(200);
    doc.line(MARGIN, y, PAGE_W - MARGIN, y);
    y += 14;
  };

  const field = (label: string, value: string) => {
    room(16);
    doc.setFontSize(9);
    doc.setTextColor(110);
    doc.text(label, MARGIN, y);
    doc.setTextColor(0);
    doc.text(value, MARGIN + 130, y);
    y += 15;
  };

  /** One table with fixed column x-offsets; status column may be tinted. */
  const table = (
    headers: string[],
    xs: number[],
    rows: string[][],
    tint?: (row: string[]) => [number, number, number] | null,
  ) => {
    room(30);
    doc.setFontSize(8);
    doc.setTextColor(110);
    headers.forEach((h, i) => doc.text(h, MARGIN + xs[i], y));
    doc.setTextColor(0);
    y += 4;
    doc.setDrawColor(210);
    doc.line(MARGIN, y, PAGE_W - MARGIN, y);
    y += 12;

    doc.setFontSize(9);
    for (const row of rows) {
      room(16);
      row.forEach((cell, i) => {
        const width = (xs[i + 1] ?? BODY_W) - xs[i] - 6;
        const lines = doc.splitTextToSize(cell, Math.max(width, 40));
        const colour = i === row.length - 1 ? tint?.(row) : null;
        if (colour) doc.setTextColor(colour[0], colour[1], colour[2]);
        doc.text(lines.slice(0, 2), MARGIN + xs[i], y);
        doc.setTextColor(0);
      });
      y += 15;
    }
    y += 8;
  };

  const paragraph = (text: string, size = 9) => {
    doc.setFontSize(size);
    for (const line of doc.splitTextToSize(text, BODY_W)) {
      room(14);
      doc.text(line, MARGIN, y);
      y += 12;
    }
    y += 6;
  };

  const GREEN: [number, number, number] = [21, 128, 61];
  const RED: [number, number, number] = [185, 28, 28];
  const statusTint = (row: string[]): [number, number, number] | null => {
    const value = row[row.length - 1];
    if (value === "Compliant" || value === "Reviewed") return GREEN;
    if (value === "Needs Review") return RED;
    return null;
  };

  /* ---- Header ---- */
  doc.setFontSize(13);
  doc.setFont("helvetica", "bold");
  doc.text("QRA", MARGIN, y);
  doc.setFontSize(14);
  doc.text("Analytical Batch Review Record", MARGIN, y + 24);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(90);
  doc.text(
    [batch.arNumber, batch.product, `Batch ${batch.batchNumber}`],
    PAGE_W - MARGIN,
    y,
    { align: "right" },
  );
  doc.setTextColor(0);
  y += 52;
  doc.setDrawColor(160);
  doc.line(MARGIN, y, PAGE_W - MARGIN, y);
  y += 22;

  /* ---- 1. Batch details ---- */
  heading("1. Batch Details");
  field("AR Number", batch.arNumber);
  field("Product", batch.product);
  field("Batch Number", batch.batchNumber);
  field("Analyst", batch.analyst);
  field("Reviewer", batch.reviewerName);
  field("Review Date", reviewDate);
  field("SLA Status", slaLabel);
  y += 10;

  /* ---- 2. Review summary ---- */
  heading("2. Review Summary");
  const summaryRows = batch.tests.map((test) => {
    const applicable = applicableSections(test);
    const statuses = sectionStatuses[test.id] ?? {};
    const reviewed = applicable.filter((s) => statuses[s.type] === "Reviewed").length;
    const findings = applicable.reduce(
      (n, s) => n + s.actualEntries.filter((e) => e.status === "flagged").length,
      0,
    );
    return [
      `${test.name} (${test.methodType})`,
      `${reviewed} / ${applicable.length}`,
      String(findings),
      findings === 0 ? "Compliant" : "Needs Review",
    ];
  });
  table(
    ["Test", "Sections Reviewed", "Findings", "Status"],
    [0, 170, 290, 370],
    summaryRows,
    statusTint,
  );

  /* ---- 3. Checklist ---- */
  heading("3. Checklist");
  const checklistRows: string[][] = [];
  for (const test of batch.tests) {
    const statuses = sectionStatuses[test.id];
    for (const section of test.sections) {
      const { ref, description } = splitChecklistReference(
        CHECKLIST_REFERENCES[section.type],
      );
      checklistRows.push([
        ref,
        description,
        test.name,
        checklistStatus(section, statuses),
      ]);
    }
  }
  table(
    ["Checklist Ref", "Description", "Test", "Status"],
    [0, 80, 300, 380],
    checklistRows,
    statusTint,
  );

  /* ---- 4. Findings ---- */
  heading("4. Findings");
  const findings: string[] = [];
  for (const test of batch.tests) {
    for (const section of applicableSections(test)) {
      for (const entry of section.actualEntries) {
        if (entry.status !== "flagged") continue;
        findings.push(
          `${test.name} > ${SECTION_LABELS[section.type]} > ${entry.label} — ${entry.finding ?? ""}`,
        );
      }
    }
  }
  if (findings.length === 0) {
    paragraph("No compliance exceptions identified across the reviewed sections.");
  } else {
    for (const line of findings) paragraph(line);
  }

  /* ---- Reviewer notes ---- */
  heading("5. Reviewer Notes");
  paragraph(reviewerNotes.trim() || "No notes recorded during this review.");

  /* ---- Disposition ---- */
  heading("6. QA Disposition");
  paragraph(
    "Record the batch disposition in Caliber LIMS. This review does not constitute batch approval or release.",
  );

  footer();
  return doc;
}

/** Section outcome labels reused by the on-screen record. */
export const recordLabelFor = sectionRecordLabel;
